name: "CKAN NBs CI workflow"


on:
  push:
    branches: [ githubactions ]
  # schedule:
  #     - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month     
      
jobs:



  ubuntu-latest-conda-job:
    name: "CKAN  ubuntu-latest"
    runs-on: ubuntu-latest
    # env:
    #   REPO: "threathunt"
    #   IMAGE: "jpnb"
    #   # https://docs.github.com/en/actions/learn-github-actions/environment-variables
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status    
    # - name: "make image"
    #   run: |
    #       set -x  
    #       sudo make deploy-ckan        
    - name: "docker-compose --version"
      run: |
           pwd
           whoami
           sudo apt-get -qq update
           docker-compose --version
    - name: "git clone"
      run: |
           pwd
           whoami
           cd /tmp
           git clone https://github.com/ckan/ckan.git 
           cd ckan          
           git checkout tags/ckan-2.9.5
           cp contrib/docker/.env.template contrib/docker/.env
           cat contrib/docker/.env
    - name: "docker-compose up -d --build  "
      run: |
           pwd
           whoami
           cd /tmp/ckan
           sudo usermod -aG docker $USER # Add your user to the docker group\
           id $USER  
           cd contrib/docker
           docker-compose up -d --build        
