name: "threat hunting w jupyter NBs CI workflow"


on:
  push:
    branches: [ githubactions ]
  # schedule:
  #     - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month     
      
jobs:



  ubuntu-latest-conda-job:
    name: "ubuntu-latest"
    runs-on: ubuntu-latest
    env:
      # DATE_INFO: $(date '+%Y%m%d')
      REPO_NAME: "threathunt"
      IMAGE_NAME: "jpnb"
      # https://docs.github.com/en/actions/learn-github-actions/environment-variables
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  
    # - name: "build image"
    #   run: docker build . -t test  
    - name: "build image"
      run: |
          set -x
          echo $(date '+%Y%m%d')
          DATE_INFO=$(date '+%Y%m%d')
          echo $DATE_INFO
          echo $DATE_INFO.$GITHUB_RUN_ID
          # docker build . -t $REPO/$IMAGE_NAME:$DATE_INFO.$GITHUB_RUN_ID
          # docker build . -t $REPO/$IMAGE_NAME:$DATE
    # - name: "deploy image"
    #   run: |
    #        docker tag $REPO/$IMAGE_NAME:$DATE.$GITHUB_RUN_ID $REPO/$IMAGE_NAME:latest          
    #        docker tag $REPO/$IMAGE_NAME $REPO/$IMAGE_NAME:$DATE
    #        docker images
    #        echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
    # - name: "deploy conda-latest"
    #   run: sudo make deploy-conda-latest
